import React from 'react'

export default function About() {
  return (
    <section className="py-16 dotted">
    <div className="container mx-auto text-center">
      <h2 className="font-sans Montserrat  text-xl font-bold text-amber-500	  mb-8">About Us</h2>
      <p className=" font-sans	 Montserrat text-2xl  text-gray-700   font-medium	 mx-auto">
      <span className="text-[#5DB85E] " >EERC </span>  
      is a consulting and research institute registered in 6th May 2016 in
       the Office of Company Registrar at Tripureshwor, Kathmandu.  
      </p><br></br>
      <p className=" font-sans	 Montserrat text-xl  text-gray-600   font-medium	 mx-auto">
      Company  has an interdisciplinary team dedicated to understand the problems 
      of development field relating to environment nexus and their potential solutions.
      </p> 

      <p className= " font-sans	 Montserrat text-xl  text-gray-600   font-medium	 mx-auto">
      The organization is built on a foundation of scientific excellence, interdisciplinary
       perspective and the momentum generated by dynamic researcher. In the field of development
        including environmentalists, engineer, agriculture specialist, IT professional and other.</p>
    </div>
  </section>
  )
}
